 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   test:
    description: Setup and run application tests
    executor: win/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "Dapper.SqlGenerator/Dapper.SqlGenerator.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "Dapper.SqlGenerator/Dapper.SqlGenerator.csproj" }}
      - run:
          name: "Run Application Tests"
          command: dotnet test -v n --results-directory:TestResults --collect:"Code Coverage" --test-adapter-path:. --logger:junit
      - store_test_results:
          path: C:\Users\circleci\project\TestResults\TestResults.xml
      - store_artifacts:
          path: C:\Users\circleci\project\TestResults
   build:
     description: Build application with Release configuration
     executor: win/default
     steps:
       - checkout
       - run:
          name: "Build Application according to some given configuration"
          command: dotnet build --configuration Release
 workflows:
   test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test