name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test -v n --results-directory:. --test-adapter-path:. --logger:"nunit;LogFilePath=..\TestResults\{assembly}.xml"
    - name: Report Tests
      uses: MirrorNG/nunit-reporter@v1.0.11
      if: always()
      with:
        path: 'TestResults/*.xml'
        access-token: ${{secrets.GITHUB_TOKEN}}
